@ -1,52 +1,6 @@
--통신사 테이블 생성
DROP TABLE BIZ;
CREATE TABLE BIZ (
	BIZ_NO	NUMBER	NOT NULL,
	BIZ_NAME	VARCHAR2(20)	NULL,
	BIZ_SSN	VARCHAR2(30)	NULL,
	BIZ_CRN	VARCHAR2(20)	NULL,
	BIZ_ID	VARCHAR2(30)	NULL,
	BIZ_PW	VARCHAR2(30)	NULL,
	BIZ_EMAIL	VARCHAR2(50)	NULL,
	BIZ_PHONE	VARCHAR2(20)	NULL,
	BIZ_FAX	VARCHAR2(20)	NULL,
	BIZ_OWNER_NAME	VARCHAR2(10)	NULL,
	BIZ_HP	VARCHAR2(100)	NULL,
	BIZ_LOCATION	VARCHAR2(200)	NULL,
	BIZ_CARD_PAY_DATE	VARCHAR2(20)	NULL,
	BIZ_ACC_PAY_DATE	VARCHAR2(20)	NULL,
	BIZ_CERTIFY	VARCHAR2(10)	NULL,
	BIZ_BEGIN_TIME	VARCHAR2(20)	NULL,
	BIZ_END_TIME	VARCHAR2(20)	NULL,
	BIZ_CLOSED_DAY	VARCHAR2(20)	NULL,
	SERVICE_SKT	VARCHAR2(20)	NULL,
	SERVICE_KT	VARCHAR2(20)	NULL,
	SERVICE_LGU	VARCHAR2(20)	NULL,
	PAYMENT_CARD	VARCHAR2(50)	NULL,
	PAYMENT_ACC	VARCHAR2(50)	NULL,
	BIZ_REVIEW_STAR	NUMBER	NULL,
	PHONE_OP_TIME	VARCHAR2(20)	NULL,
	PHONE_OP_TIME_USIM	VARCHAR2(20)	NULL,
	NETWORK	VARCHAR2(50)	NULL,
	WRITE_DATE	DATE	NOT NULL,
	UPDATE_DATE	DATE	NULL,
	LOGO_RENAME_FILENAME	VARCHAR2(100)	NULL
);

-- 통신사 테이블 BIZ_NAME 크기 수정
ALTER TABLE BIZ
MODIFY (BIZ_NAME VARCHAR2(30));

ALTER TABLE BIZ ADD CONSTRAINT PK_BIZ PRIMARY KEY (
	BIZ_NO
);

--BIZ 시퀀스 생성
DROP SEQUENCE BIZ_SEQ;
CREATE SEQUENCE BIZ_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       NOCYCLE
       NOCACHE
       ORDER;
-- BIZ_SEQ.NEXTVAL


desc biz;





