--통신사 정보 입력
INSERT INTO BIZ VALUES (BIZ_SEQ.NEXTVAL, 
                        'KCTV',
                        '220111-0013888',
                        '616-81-11863',
                        'kctv',
                        'kctv',
                        'k2j@kctvjeju.com',
                        '064-741-7777',
                        '064-748-0125',
                        '공성용',
                        'https://www.kctvjeju.com/',
                        '(63142) 제주특별자치도 제주시 아연로2(연동 422)',
                        null,
                        null,
                        null,
                        '9:00',
                        '18:00',
                        '토,일,공휴일',
                        '064-741-7784',
                        NULL,
                        '877-7030',
                        '매월 9일',
                        '매월 5일',
                        '4.4',
                        '평균 2일',
                        '평균 0.2일',
                        'SK망,KT망,LG망',
                        SYSDATE,
                        NULL,
                        NULL
);
SELECT * FROM BIZ;
commit; 