--통신사 정보 입력
INSERT INTO BIZ VALUES (BIZ_SEQ.NEXTVAL, 
                        'KCTV',
                        '220111-0013888',
                        '616-81-11863',
                        'kctv',
                        'kctv',
                        'k2j@kctvjeju.com',
                        '064-741-7777',
                        '064-748-0125',
                        '공성용',
                        'https://www.kctvjeju.com/',
                        '(63142) 제주특별자치도 제주시 아연로2(연동 422)',
                        null,
                        null,
                        null,
                        '9:00',
                        '18:00',
                        '토,일,공휴일',
                        '064-741-7784',
                        NULL,
                        '877-7030',
                        '매월 9일',
                        '매월 5일',
                        '4.4',
                        '평균 2일',
                        '평균 0.2일',
                        'SK망,KT망,LG망',
                        SYSDATE,
                        NULL,
                        NULL
);
INSERT INTO BIZ VALUES (BIZ_SEQ.NEXTVAL, 
                        '위너스텔',
                        '189332-4672215',
                        '106-81-85679',
                        'idowell',
                        'idowell',
                        'idowell@idowell.com',
                        '1688-8466',
                        '1688-8467',
                        '서욱진',
                        'www.idowell.co.kr/',
                        '서울시 금천구 디지털로 121 에이스가산타워 1303호',
                        '매월 23일',
                        '매월 25일',
                        '9:00',
                        '18:00',
                        '토,일,공휴일',
                        NULL,
                        '1688-8466',
                         NULL,
                        '3.9',
                        '평균 1일',
                        '평균 1일',
                        'KT망',
                        SYSDATE,
                        NULL,
                        NULL
);
INSERT INTO BIZ VALUES (BIZ_SEQ.NEXTVAL, 
                        '유니컴즈',
                        '134111-0211768',
                        '138-81-70324',
                        'unicomz',
                        'unicomz',
                        'unicomz@unicomz.com',
                        '070-7945-0525',
                        '031-624-2178',
                        '정성태',
                        'www.mobing.co.kr',
                        '경기도 군포시 엘에스로166번길 8 (금정동)',
                        '매월 10일',
                        '매월 10일',
                        '9:00',
                        '18:00',
                        '토,일,공휴일',
                        '1899-3666',
                        '1666-9980',
                        '1688-2964',
                        '4.4',
                        '평균 2.9일',
                        '평균 0.4일',
                        'SK망,KT망,LG망',
                        SYSDATE,
                        NULL,
                        NULL
);
INSERT INTO BIZ VALUES (BIZ_SEQ.NEXTVAL, 
                        '인스코비',
                        '110111-0018592',
                        '119-81-03654',
                        'inscobee',
                        'inscobee',
                        'Inscobee@Inscobee.co.kr',
                        '070-7510-3448',
                        '02-544-9641',
                        '유인수',
                        'www.inscobee.com',
                        '서울특별시 금천구 디지털로 130 남성프라자 613호',
                        '매월 9일',
                        '매월 15일',
                        '9:00',
                        '18:00',
                        '토,일,공휴일',
                        '1661-2207',
                        '1577-4551',
                        '1588-3615',
                        '4.5',
                        '평균 2일',
                        '평균 0.5일',
                        'SK망,KT망,LG망',
                        SYSDATE,
                        NULL,
                        NULL
);
INSERT INTO BIZ VALUES (BIZ_SEQ.NEXTVAL, 
                        '와이엘랜드',
                        '129434-9087465',
                        '104-86-21733',
                        'yytel',
                        'yytel',
                        'yytel@yytel.com',
                        '1644-5646',
                        '0505-999-5646',
                        '김병주',
                        'www.yytelecom.co.kr',
                        '경기도 성남시 분당구 판교역로 230 (삼평동) 삼환하이펙스 B동 903호',
                        '매월 10일',
                        '매월 20일',
                        '9:00',
                        '18:00',
                        '토,일,공휴일',
                        null,
                        '1661-5146',
                        '1661-5647',
                        '3.8',
                        '평균 3일',
                        '평균 1.8일',
                        'KT망,LG망',
                        SYSDATE,
                        NULL,
                        NULL
);

SELECT * FROM BIZ;
commit; 